import {
  IconChrono,
  IconVirelangue,
  IconDoublage,
  IconAveugle,
  IconMenteur,
  IconConversation,
  IconMemoire,
  IconImprovisation,
  IconCalcul,
  IconCadenas,
  IconDeclaration,
  IconClavier,
  IconBuzzer,
  IconCorde,
  IconCamembertVote,
  IconSimon,
  IconCrayonTactile,
  IconMasque,
  IconRoue,
} from '../components/icons.jsx';

// styleJeux.js — icône + couleurs par mini-jeu, partagées entre l'écran de
// choix du jeu et l'écran de règles.

export const STYLE_PAR_JEU = {
  'virelangue-express': { Icone: IconVirelangue, bg: 'var(--accent-lime)', couleur: 'var(--accent-lime)' },
  'memoire-flash': { Icone: IconMemoire, bg: 'var(--bg-deep)', couleur: 'var(--accent-cyan)', contour: 'var(--accent-cyan)' },
  'calcul-eclair': { Icone: IconCalcul, bg: 'var(--accent-lime)', couleur: 'var(--accent-lime)' },
  'texte-corse': { Icone: IconVirelangue, bg: 'var(--bg-deep)', couleur: 'var(--accent-magenta)', contour: 'var(--accent-magenta)' },
  'mot-surprise': { Icone: IconImprovisation, bg: 'var(--accent-lime)', couleur: 'var(--accent-lime)' },
  'conversation': { Icone: IconConversation, bg: 'var(--bg-deep)', couleur: 'var(--accent-magenta)', contour: 'var(--accent-magenta)' },
  'improvisation-titre': { Icone: IconImprovisation, bg: 'var(--accent-violet)', couleur: 'var(--accent-violet)' },
  'categories-chrono': { Icone: IconAveugle, bg: 'var(--accent-cyan)', couleur: 'var(--accent-cyan)' },
  'histoire-plusieurs-voix': { Icone: IconConversation, bg: 'var(--bg-deep)', couleur: 'var(--accent-magenta)', contour: 'var(--accent-magenta)' },
  'speed-dating-improbable': { Icone: IconImprovisation, bg: 'var(--accent-yellow)', couleur: 'var(--accent-yellow)' },
  'proces-fictif': { Icone: IconMenteur, bg: 'var(--bg-deep)', couleur: 'var(--accent-magenta)', contour: 'var(--accent-magenta)' },
  'emission-tele-achat': { Icone: IconDoublage, bg: 'var(--bg-deep)', couleur: 'var(--accent-yellow)', contour: 'var(--accent-yellow)' },
  'evasion-express': { Icone: IconCadenas, bg: 'var(--accent-lime)', couleur: 'var(--accent-lime)' },
  'declaration': { Icone: IconDeclaration, bg: 'var(--accent-magenta)', couleur: 'var(--accent-magenta)' },
  'texto-sous-pression': { Icone: IconClavier, bg: 'var(--accent-cyan)', couleur: 'var(--accent-cyan)' },

  'duel-buzzer': { Icone: IconBuzzer, bg: 'var(--accent-cyan)', couleur: 'var(--accent-cyan)' },
  'vision-floue': { Icone: IconBuzzer, bg: 'var(--bg-deep)', couleur: 'var(--accent-magenta)', contour: 'var(--accent-magenta)' },
  'question-eclair': { Icone: IconBuzzer, bg: 'var(--accent-yellow)', couleur: 'var(--accent-yellow)' },
  'compte-est-bon-express': { Icone: IconBuzzer, bg: 'var(--accent-lime)', couleur: 'var(--accent-lime)' },
  'tir-a-la-corde': { Icone: IconCorde, bg: 'var(--bg-deep)', couleur: 'var(--accent-cyan)', contour: 'var(--accent-cyan)' },
  'le-trone': { Icone: IconCorde, bg: 'var(--accent-yellow)', couleur: 'var(--accent-yellow)' },
  'surchauffe': { Icone: IconCorde, bg: 'var(--bg-deep)', couleur: 'var(--accent-magenta)', contour: 'var(--accent-magenta)' },
  'marathon-des-doigts': { Icone: IconCorde, bg: 'var(--accent-lime)', couleur: 'var(--accent-lime)' },
  'sondage-choc': { Icone: IconCamembertVote, bg: 'var(--accent-yellow)', couleur: 'var(--accent-yellow)' },
  'qui-ferait-ca': { Icone: IconCamembertVote, bg: 'var(--bg-deep)', couleur: 'var(--accent-violet)', contour: 'var(--accent-violet)' },
  'plus-ou-moins': { Icone: IconCamembertVote, bg: 'var(--accent-cyan)', couleur: 'var(--accent-cyan)' },
  'juste-prix-express': { Icone: IconCamembertVote, bg: 'var(--accent-lime)', couleur: 'var(--accent-lime)' },
  'vote-de-la-honte': { Icone: IconCamembertVote, bg: 'var(--bg-deep)', couleur: 'var(--accent-magenta)', contour: 'var(--accent-magenta)' },
  'simon-dit-numerique': { Icone: IconSimon, bg: 'var(--bg-deep)', couleur: 'var(--accent-violet)', contour: 'var(--accent-violet)' },
  'memoire-flash-collective': { Icone: IconSimon, bg: 'var(--accent-cyan)', couleur: 'var(--accent-cyan)' },
  'cadavre-exquis-numerique': { Icone: IconCrayonTactile, bg: 'var(--accent-yellow)', couleur: 'var(--accent-yellow)' },
  'le-traitre': { Icone: IconMasque, bg: 'var(--accent-magenta)', couleur: 'var(--accent-magenta)' },
  'espion-parmi-nous': { Icone: IconMasque, bg: 'var(--bg-deep)', couleur: 'var(--accent-cyan)', contour: 'var(--accent-cyan)' },
  'roue-du-destin': { Icone: IconRoue, bg: 'var(--accent-yellow)', couleur: 'var(--accent-yellow)' },
  'croquis-en-direct': { Icone: IconCrayonTactile, bg: 'var(--accent-lime)', couleur: 'var(--accent-lime)' },
  'coffre-fort': { Icone: IconCadenas, bg: 'var(--bg-deep)', couleur: 'var(--accent-violet)', contour: 'var(--accent-violet)' },
  'chrono-aveugle': { Icone: IconChrono, bg: 'var(--accent-magenta)', couleur: 'var(--accent-magenta)' },
  'chaise-musicale-numerique': { Icone: IconCorde, bg: 'var(--bg-deep)', couleur: 'var(--accent-magenta)', contour: 'var(--accent-magenta)' },
  'marche-noir': { Icone: IconCamembertVote, bg: 'var(--bg-deep)', couleur: 'var(--accent-violet)', contour: 'var(--accent-violet)' },
  'dessine-et-devine': { Icone: IconCrayonTactile, bg: 'var(--accent-cyan)', couleur: 'var(--accent-cyan)' },
  'chaud-froid': { Icone: IconCalcul, bg: 'var(--bg-deep)', couleur: 'var(--accent-cyan)', contour: 'var(--accent-cyan)' },
  'ni-vu-ni-connu': { Icone: IconBuzzer, bg: 'var(--bg-deep)', couleur: 'var(--accent-magenta)', contour: 'var(--accent-magenta)' },
  'guerre-des-watts': { Icone: IconCorde, bg: 'var(--accent-cyan)', couleur: 'var(--accent-cyan)' },
  'ames-soeurs': { Icone: IconMasque, bg: 'var(--bg-deep)', couleur: 'var(--accent-violet)', contour: 'var(--accent-violet)' },
  'vrai-ou-intox': { Icone: IconCamembertVote, bg: 'var(--accent-lime)', couleur: 'var(--accent-lime)' },
};
