import {
  IconVirelangue,
  IconAccent,
  IconSansRire,
  IconChrono,
  IconDoublage,
  IconBruit,
  IconChant,
  IconAveugle,
  IconMenteur,
  IconStatue,
  IconConversation,
  IconMemoire,
  IconImprovisation,
  IconCalcul,
  IconSondage,
  IconDetective,
  IconCadenas,
  IconDeclaration,
  IconClavier,
  IconBuzzer,
  IconCorde,
  IconCamembertVote,
  IconSimon,
  IconCrayonTactile,
  IconMasque,
  IconRoue,
} from '../components/icons.jsx';

// styleJeux.js — icône + couleurs par mini-jeu, partagées entre l'écran de
// choix du jeu et l'écran de règles.

export const STYLE_PAR_JEU = {
  'virelangue-express': { Icone: IconVirelangue, bg: 'var(--accent-lime)', couleur: 'var(--accent-lime)' },
  'accent-surprise': { Icone: IconAccent, bg: 'var(--accent-yellow)', couleur: 'var(--accent-yellow)' },
  'sans-rire': { Icone: IconSansRire, bg: 'var(--accent-magenta)', couleur: 'var(--accent-magenta)' },
  'defi-chrono-absurde': { Icone: IconChrono, bg: 'var(--accent-cyan)', couleur: 'var(--accent-cyan)' },
  'doublage-sauvage': { Icone: IconDoublage, bg: 'var(--accent-violet)', couleur: 'var(--accent-violet)' },
  'devine-le-bruit': { Icone: IconBruit, bg: 'var(--bg-deep)', couleur: 'var(--accent-lime)', contour: 'var(--accent-lime)' },
  'chant-impose': { Icone: IconChant, bg: 'var(--bg-deep)', couleur: 'var(--accent-yellow)', contour: 'var(--accent-yellow)' },
  'dessine-a-laveugle': { Icone: IconAveugle, bg: 'var(--bg-deep)', couleur: 'var(--accent-cyan)', contour: 'var(--accent-cyan)' },
  'le-menteur': { Icone: IconMenteur, bg: 'var(--bg-deep)', couleur: 'var(--accent-magenta)', contour: 'var(--accent-magenta)' },
  'memoire-flash': { Icone: IconMemoire, bg: 'var(--bg-deep)', couleur: 'var(--accent-cyan)', contour: 'var(--accent-cyan)' },
  'calcul-eclair': { Icone: IconCalcul, bg: 'var(--accent-lime)', couleur: 'var(--accent-lime)' },
  'texte-corse': { Icone: IconVirelangue, bg: 'var(--bg-deep)', couleur: 'var(--accent-magenta)', contour: 'var(--accent-magenta)' },
  'mot-surprise': { Icone: IconImprovisation, bg: 'var(--accent-lime)', couleur: 'var(--accent-lime)' },
  'statue-surprise': { Icone: IconStatue, bg: 'var(--bg-deep)', couleur: 'var(--accent-violet)', contour: 'var(--accent-violet)' },
  'conversation': { Icone: IconConversation, bg: 'var(--bg-deep)', couleur: 'var(--accent-magenta)', contour: 'var(--accent-magenta)' },
  'improvisation': { Icone: IconImprovisation, bg: 'var(--accent-yellow)', couleur: 'var(--accent-yellow)' },
  'improvisation-titre': { Icone: IconImprovisation, bg: 'var(--accent-violet)', couleur: 'var(--accent-violet)' },
  'alphabet-express': { Icone: IconVirelangue, bg: 'var(--accent-cyan)', couleur: 'var(--accent-cyan)' },
  'memoire-groupe': { Icone: IconMemoire, bg: 'var(--bg-deep)', couleur: 'var(--accent-magenta)', contour: 'var(--accent-magenta)' },
  'sondage-predictif': { Icone: IconSondage, bg: 'var(--accent-yellow)', couleur: 'var(--accent-yellow)' },
  'le-detective': { Icone: IconDetective, bg: 'var(--bg-deep)', couleur: 'var(--accent-violet)', contour: 'var(--accent-violet)' },
  'categories-chrono': { Icone: IconAveugle, bg: 'var(--accent-cyan)', couleur: 'var(--accent-cyan)' },
  'association-chaine': { Icone: IconConversation, bg: 'var(--accent-lime)', couleur: 'var(--accent-lime)' },
  'histoire-plusieurs-voix': { Icone: IconConversation, bg: 'var(--bg-deep)', couleur: 'var(--accent-magenta)', contour: 'var(--accent-magenta)' },
  'speed-dating-improbable': { Icone: IconImprovisation, bg: 'var(--accent-yellow)', couleur: 'var(--accent-yellow)' },
  'proces-fictif': { Icone: IconMenteur, bg: 'var(--bg-deep)', couleur: 'var(--accent-magenta)', contour: 'var(--accent-magenta)' },
  'emission-tele-achat': { Icone: IconDoublage, bg: 'var(--bg-deep)', couleur: 'var(--accent-yellow)', contour: 'var(--accent-yellow)' },
  'evasion-express': { Icone: IconCadenas, bg: 'var(--accent-lime)', couleur: 'var(--accent-lime)' },
  'declaration': { Icone: IconDeclaration, bg: 'var(--accent-magenta)', couleur: 'var(--accent-magenta)' },
  'texto-sous-pression': { Icone: IconClavier, bg: 'var(--accent-cyan)', couleur: 'var(--accent-cyan)' },

  'duel-buzzer': { Icone: IconBuzzer, bg: 'var(--accent-cyan)', couleur: 'var(--accent-cyan)' },
  'vision-floue': { Icone: IconBuzzer, bg: 'var(--bg-deep)', couleur: 'var(--accent-magenta)', contour: 'var(--accent-magenta)' },
  'question-eclair': { Icone: IconBuzzer, bg: 'var(--accent-yellow)', couleur: 'var(--accent-yellow)' },
  'compte-est-bon-express': { Icone: IconBuzzer, bg: 'var(--accent-lime)', couleur: 'var(--accent-lime)' },
  'tir-a-la-corde': { Icone: IconCorde, bg: 'var(--bg-deep)', couleur: 'var(--accent-cyan)', contour: 'var(--accent-cyan)' },
  'le-trone': { Icone: IconCorde, bg: 'var(--accent-yellow)', couleur: 'var(--accent-yellow)' },
  'surchauffe': { Icone: IconCorde, bg: 'var(--bg-deep)', couleur: 'var(--accent-magenta)', contour: 'var(--accent-magenta)' },
  'marathon-des-doigts': { Icone: IconCorde, bg: 'var(--accent-lime)', couleur: 'var(--accent-lime)' },
  'sondage-choc': { Icone: IconCamembertVote, bg: 'var(--accent-yellow)', couleur: 'var(--accent-yellow)' },
  'qui-ferait-ca': { Icone: IconCamembertVote, bg: 'var(--bg-deep)', couleur: 'var(--accent-violet)', contour: 'var(--accent-violet)' },
  'plus-ou-moins': { Icone: IconCamembertVote, bg: 'var(--accent-cyan)', couleur: 'var(--accent-cyan)' },
  'juste-prix-express': { Icone: IconCamembertVote, bg: 'var(--accent-lime)', couleur: 'var(--accent-lime)' },
  'vote-de-la-honte': { Icone: IconCamembertVote, bg: 'var(--bg-deep)', couleur: 'var(--accent-magenta)', contour: 'var(--accent-magenta)' },
  'simon-dit-numerique': { Icone: IconSimon, bg: 'var(--bg-deep)', couleur: 'var(--accent-violet)', contour: 'var(--accent-violet)' },
  'memoire-flash-collective': { Icone: IconSimon, bg: 'var(--accent-cyan)', couleur: 'var(--accent-cyan)' },
  'cadavre-exquis-numerique': { Icone: IconCrayonTactile, bg: 'var(--accent-yellow)', couleur: 'var(--accent-yellow)' },
  'le-traitre': { Icone: IconMasque, bg: 'var(--accent-magenta)', couleur: 'var(--accent-magenta)' },
  'espion-parmi-nous': { Icone: IconMasque, bg: 'var(--bg-deep)', couleur: 'var(--accent-cyan)', contour: 'var(--accent-cyan)' },
  'roue-du-destin': { Icone: IconRoue, bg: 'var(--accent-yellow)', couleur: 'var(--accent-yellow)' },
  'croquis-en-direct': { Icone: IconCrayonTactile, bg: 'var(--accent-lime)', couleur: 'var(--accent-lime)' },
};
